services:
  api_host: "10.76.32.4:900"
  api_base_path: "/nomad-oasis"
  admin_user_id: "1057a0df-0b48-4840-9f57-3603fa59d0cb"
  
ui:
  apps:
    exclude: ['app1']
    options:
      "app1": entries
        
          
oasis:
  is_oasis: true
  uses_central_user_management: true

north:
  jupyterhub_crypt_key: "978bfb2e13a8448a253c629d8dd84ff89587f30e635b753153960930cad9d36d"
  #hub_connect_ip: 'host.docker.internal' # for Windows
  tools:
    options:
      jupyter:
        image: ghcr.io/kaikoebnick/kaffee/jupyter:main

#keycloak:
#  server_url: 'http://keycloak:8080/auth/'
#  public_server_url: 'http://localhost/keycloak/auth/'
#  realm_name: nomad
#  username: 'admin'
#  password: 'password'

meta:
  deployment: "oasis"
  deployment_url: "http://10.76.32.4:900/api"
  maintainer_email: "kai.koebnick@fau.de"

logtransfer:
  enabled: false

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1

#plugins:
  #options:
    #custom-schema:
      #python_package: custom-schema
